server:
  port: 8761

spring:
  application:
    name: service-discovery
  output:
    ansi:
      enabled: always

eureka:
  client:
    # 애플리케이션(클라이언트)이 eureka 서버에 자신의 인스턴스를 등록할지 여부
    # eureka 서버 자체나 클라이언트로만 동작하는 애플리케이션일 경우 자신을 등록할 필요가 없다
    register-with-eureka: false
    # 클라이언트가 eureka 서버로부터 서비스 레지스트리를 가져올지 여부
    # eureka 서버는 다른 서비스들의 레지스트리를 관리하는 역할을 수행하기 때문에,
    # 자신을 다시 서버에 등록하거나 다른 서비스 목록을 받아올 필요가 없다
    fetch-registry: false