server:
  port: 8888

spring:
  output:
    ansi:
      enabled: always
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
#    active: local
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/13-lecture/dowon-lee/work/native-file-repo
        git:
#          uri: file:///home/zerone/13-lecture/dowon-lee/work/git-local-repo
          uri: https://github.com/xxxzerone/demo-spring-cloud-config.git
#          usename: [your username]
#          password: [your password]

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh